/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRepos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorkflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRuns"];
        put?: never;
        post: operations["startRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pauseRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/rewind": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rewindRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description WebSocket upgrade. Server sends JSON TimelineEvent messages until the
         *     run ends. Use a WebSocket client; not covered by the generated HTTP client.
         */
        get: operations["followRunEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Repo: {
            name: string;
            /** @description Absolute path of the Repo working tree */
            absolutePath: string;
        };
        StartRequest: {
            workflowId: string;
            /** @description Override Project; empty uses Workflow.defaultProject */
            projectPath?: string;
            /** @description stepId.inputName → value */
            inputOverrides?: {
                [key: string]: string;
            };
            /** @description processId → args */
            argumentOverrides?: {
                [key: string]: string[];
            };
        };
        RewindRequest: {
            stepId: string;
        };
        WorkflowRun: {
            id: string;
            workflowId: string;
            projectPath: string;
            status: string;
            cursorStepId?: string;
            stepRuns?: components["schemas"]["StepRun"][];
            processRuns?: components["schemas"]["ProcessRun"][];
        };
        StepRun: {
            stepId: string;
            status: string;
            /** @description Loop iteration when relevant (0 omitted) */
            iteration?: number;
        };
        ProcessRun: {
            processId: string;
            stepId?: string;
            status: string;
            exitCode?: number;
        };
        Workflow: {
            id: string;
            name: string;
            defaultProject?: string;
            steps: components["schemas"]["StepView"][];
            connections: components["schemas"]["Connection"][];
        };
        StepView: {
            id: string;
            name: string;
            mode: string;
            inputs?: components["schemas"]["InputView"][];
            outputs?: components["schemas"]["OutputView"][];
            visualization?: components["schemas"]["Visualization"];
        };
        Visualization: {
            position?: components["schemas"]["VizPosition"];
        };
        VizPosition: {
            x: number;
            y: number;
        };
        InputView: {
            name: string;
            source?: components["schemas"]["SourceView"];
        };
        OutputView: {
            name: string;
            value?: string;
        };
        SourceView: {
            stepId: string;
            output: string;
        };
        Connection: {
            sourceStepId: string;
            sourceOutput: string;
            targetStepId: string;
            targetInput: string;
        };
        /** @description JSONL / WebSocket timeline event */
        TimelineEvent: {
            type: string;
            ts?: string;
            runId?: string;
            workflowId?: string;
            processId?: string;
            stepId?: string;
            data?: string;
            stream?: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Plain-text error */
        TextError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
    };
    parameters: {
        Id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: string;
                    };
                };
            };
        };
    };
    listRepos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered Repos from Subspace home repos.json */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repo"][];
                };
            };
            500: components["responses"]["TextError"];
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow with derived Connections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            404: components["responses"]["TextError"];
        };
    };
    listRuns: {
        parameters: {
            query?: {
                /** @description Absolute or relative Project path; empty lists all runs under StorageRoot */
                projectPath?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WorkflowRuns from memory + StorageRoot (newest id first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"][];
                };
            };
            400: components["responses"]["TextError"];
        };
    };
    startRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Started WorkflowRun */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
            400: components["responses"]["TextError"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WorkflowRun */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
            404: components["responses"]["TextError"];
        };
    };
    pauseRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated WorkflowRun */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
            400: components["responses"]["TextError"];
        };
    };
    resumeRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated WorkflowRun */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
            400: components["responses"]["TextError"];
        };
    };
    stopRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated WorkflowRun */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
            400: components["responses"]["TextError"];
        };
    };
    rewindRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RewindRequest"];
            };
        };
        responses: {
            /** @description Updated WorkflowRun */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRun"];
                };
            };
            400: components["responses"]["TextError"];
        };
    };
    followRunEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols (WebSocket) */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["TextError"];
        };
    };
}
